# Generated by Django 5.1.6 on 2025-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostManga',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/manga/')),
            ],
        ),
    ]
