# Generated by Django 5.1.6 on 2025-02-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanga',
            name='description',
            field=models.TextField(default='ok', max_length=4),
            preserve_default=False,
        ),
    ]
