# Generated by Django 5.1.6 on 2025-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmanga_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanga',
            name='urlImage',
            field=models.URLField(default='https://avt.mkklcdnv6temp.com/fld/7/e/14-1733299960-nw.webp'),
            preserve_default=False,
        ),
    ]
