# Generated by Django 4.2.19 on 2025-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmanga_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanga',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='postmanga',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postmanga',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
