# Generated by Django 4.2.19 on 2025-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postmanga_author_alter_postmanga_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmanga',
            name='status',
            field=models.CharField(choices=[('In corso', 'In corso'), ('Completato', 'Completato'), ('Lasciato momentaneamente', 'Lasciato momentaneamente')], default='In corso', max_length=150),
        ),
    ]
