# Generated by Django 4.2.19 on 2025-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmanga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanga',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag'),
        ),
    ]
