# Generated by Django 5.1.6 on 2025-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postmanga_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='postmanga',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
