# Generated by Django 4.2.19 on 2025-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanga',
            name='urlImage',
            field=models.URLField(max_length=300),
        ),
    ]
