# Generated by Django 4.2.19 on 2025-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postmanga_titleurl_alter_postmanga_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanga',
            name='title',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
