# Generated by Django 4.2.20 on 2025-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, default='images/userProfile/default.png', null=True, upload_to='images/userProfile/'),
        ),
    ]
